#! /bin/sh

in=$1

mkdir -p tmp
echo cOOre-compiler ====================================================
../../RTFM-cOOre-compiler/src/Main.native -gv_obj cOOre_task.gv -i $1 -o ./tmp/${in%.*}.core
dot -Tpdf cOOre_task.gv -o cOOre_task.pdf
echo core-compiler =====================================================
../../RTFM-core-compiler/src/Main.native -gv_task core_task.gv -i ./tmp/${in%.*}.core -o ../Application/autogen.c
dot -Tpdf core_task.gv -o core_task.pdf
echo gcc ===============================================================
gcc ../RTFM-PT/RTFM-PT.c -o ../bin/${in%.*} -lpthread
rm ./tmp/${in%.*}.core


