#! /bin/sh

in=$1

mkdir -p tmp
echo cOOre-compiler ====================================================
../../RTFM-cOOre-compiler/src/Main.native -i $1 -o ${in%.*}.core -D -v
echo core-compiler =====================================================
../../RTFM-core-compiler/src/Main.native -i ${in%.*}.core -o ../Application/autogen.c -D -v
echo gcc ===============================================================
gcc ../RTFM-PT/RTFM-PT.c -o ../bin/${in%.*} -lpthread