#! /bin/sh

in=$1

echo cOOre-compiler ====================================================
../../RTFM-cOOre-compiler/src/Main.native -i $1 -o ${in%.*}.core -D -v -gv_task task.gv -gv_obj obj.gv -gv_res inst.gv

echo core-compiler =====================================================
../../RTFM-core-compiler/src/Main.native -i ${in%.*}.core -o ../RTFM-PT/autogen.c -D -v

echo generating pdfs ===================================================
dot -Tpdf cOOre_task.gv -o cOOre_task.pdf

echo gcc ===============================================================
gcc ../RTFM-PT/RTFM-PT.c -o ../bin/${in%.*} -lpthread -lssl -lcrypto -I /usr/local/Cellar/openssl/1.0.1e/include -L/usr/local/Cellar/openssl/1.0.1e/lib fmemopen.c -D TRACE_WS