#! /bin/sh

in=$1

echo core-compiler =====================================================
../../RTFM-core-compiler/src/Main.native -i ${in%.*}.core -o ../Application/autogen.c
echo gcc ===============================================================
gcc ../RTFM-PT/RTFM-PT.c -o ../bin/${in%.*} -lpthread -lssl -lcrypto -I /usr/local/Cellar/openssl/1.0.1e/include -L/usr/local/Cellar/openssl/1.0.1e/lib fmemopen.c
rm ./tmp/${in%.*}.core