#!/bin/bash

##################
function if_error
##################
{
if [[ $? -ne 0 ]]; then # check return code passed to function
#print "$1 TIME:$TIME" | tee -a $LOG # if rc > 0 then print error msg and quit
exit $?
fi
}

ocamlbuild -clean
rm -rv ../../PTCORE/Application
rm -v ./Main.native
rm -v *.pdf
rm -v *.dot