#!/bin/bash

##################
function if_error
##################
{
if [[ $? -ne 0 ]]; then # check return code passed to function
#print "$1 TIME:$TIME" | tee -a $LOG # if rc > 0 then print error msg and quit
exit $?
fi
}

ocamlbuild -use-menhir Main.native
if_error "ocamlbuild"

MAKEDIR = ../../PTCORE/Application

$(shell mkdir -p $(MAKEDIR) 2>/dev/null)

./Main.native ../../PTCORE/RTFM-SRC/Application.core -o ../../PTCORE/Application/autogen.c
if_error "Main"