#!/bin/bash

##################
function if_error
##################
{
if [[ $? -ne 0 ]]; then # check return code passed to function
#print "$1 TIME:$TIME" | tee -a $LOG # if rc > 0 then print error msg and quit
exit $?
fi
}

cp ../input/f1.rtfm /media/psf/Home/Dropbox/CISTER/rtfm-core-0/examples/
cp out.pdf /media/psf/Home/Dropbox/CISTER/rtfm-core-0/figs/
 