#!/usr/bin/env bash

# Get all bats files

# For each bats file
  # Convert file name to nice string (variable_assignments.bats => "Variable Assignments")
  # echo "Testing Variable Assignments"
  # run tests
  # echo "\n"